package perpustakaan;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Briggita
 */
public class frameMain extends javax.swing.JFrame
{
    String zero_hour = "";
    String zero_minute = "";
    String zero_second = "";

    /**
     * Creates new form frameMain
     */
    public frameMain() {
        initComponents();
        selectData();
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        No = new javax.swing.JTextField();
        Judul = new javax.swing.JTextField();
        Denda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();
        Jenis = new javax.swing.JComboBox<>();
        rbBK = new javax.swing.JRadioButton();
        rbK = new javax.swing.JRadioButton();
        Refresh = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Print = new javax.swing.JButton();
        TglKembali = new com.toedter.calendar.JDateChooser();
        TglPinjam = new com.toedter.calendar.JDateChooser();
        Waktu = new javax.swing.JLabel();
        Tanggal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("RESERVASI PENGEMBALIAN BUKU PERPUSTAKAAN KOTA MALANG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 590, -1));

        jLabel2.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jLabel2.setText("No. Anggota");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jLabel3.setText("Nama Peminjam");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jLabel4.setText("Alamat Peminjam");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jLabel5.setText("Jenis Buku");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jLabel6.setText("Judul Buku");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jLabel7.setText("Tanggal Pengembalian");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jLabel8.setText("Denda Pelanggaran");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, -1));

        jLabel9.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jLabel9.setText("Status");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, -1, -1));
        jPanel1.add(No, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 220, 30));
        jPanel1.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 220, 30));

        Denda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DendaActionPerformed(evt);
            }
        });
        jPanel1.add(Denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 220, 30));

        Alamat.setColumns(20);
        Alamat.setRows(5);
        jScrollPane1.setViewportView(Alamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 220, 70));

        Jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelajaran", "Pengetahuan Umum", "Novel" }));
        Jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisActionPerformed(evt);
            }
        });
        jPanel1.add(Jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 220, 30));

        buttonGroup1.add(rbBK);
        rbBK.setText("Belum Kembali");
        jPanel1.add(rbBK, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 110, 30));

        buttonGroup1.add(rbK);
        rbK.setText("Kembali");
        jPanel1.add(rbK, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 100, 30));

        Refresh.setBackground(new java.awt.Color(0, 102, 51));
        Refresh.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 100, 30));

        Save.setBackground(new java.awt.Color(0, 102, 51));
        Save.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 100, 30));

        Clear.setBackground(new java.awt.Color(0, 102, 51));
        Clear.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 100, 30));

        Delete.setBackground(new java.awt.Color(0, 102, 51));
        Delete.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 100, 30));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NoAnggota", "NamaPeminjam", "AlamatPeminjam", "JenisBuku", "JudulBuku", "TanggalPeminjaman", "TanggalPengembalian", "DendaPelanggaran", "Status"
            }
        ));
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabel);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1150, -1));

        jLabel10.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jLabel10.setText("Tanggal Peminjaman");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));
        jPanel1.add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 220, 30));

        Print.setBackground(new java.awt.Color(0, 102, 51));
        Print.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel1.add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 510, 100, 30));
        jPanel1.add(TglKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 220, 30));
        jPanel1.add(TglPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 220, 30));

        Waktu.setFont(new java.awt.Font("Gisha", 1, 14)); // NOI18N
        Waktu.setForeground(new java.awt.Color(255, 153, 51));
        Waktu.setText("Waktu");
        jPanel1.add(Waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 130, -1, -1));

        Tanggal.setFont(new java.awt.Font("Gisha", 1, 14)); // NOI18N
        Tanggal.setForeground(new java.awt.Color(255, 153, 51));
        Tanggal.setText("Tanggal");
        jPanel1.add(Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisActionPerformed
        // TODO add your handling code here:
        if(Jenis.getSelectedItem().equals("Pelajaran"))
        {
            Judul.setText("Ilmu Pengetahuan Sosial");
        }
        if(Jenis.getSelectedItem().equals("Pengetahuan Umum"))
        {
            Judul.setText("Kebudayaan Mancanegara");
        }
        if(Jenis.getSelectedItem().equals("Novel"))
        {
            Judul.setText("Mata-Mata Pencuri Hak Waris");
        }
    }//GEN-LAST:event_JenisActionPerformed

    private void DendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DendaActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String kembali = dateFormat.format(TglKembali.getDate());
        String pinjam = dateFormat.format(TglPinjam.getDate());
        String no = No.getText();
        String nama = Nama.getText();
        String jenis = Jenis.getSelectedItem().toString();
        if("".equals(No.getText()) || "".equals(Nama.getText()) || "".equals(Alamat.getText()) || 
                "".equals(Jenis.getSelectedItem()) || "".equals(Judul.getText()) || pinjam.equals("") || 
                kembali.equals("") || "".equals(Denda.getText()))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else
        {
            String JS = "";
                if(rbK.isSelected())
                {
                    JS = "K";
                } else
                {
                    JS = "BK";
                }
            String SQL = "INSERT INTO tb_kembali (NoAnggota,NamaPeminjam,AlamatPeminjam,JenisBuku,TanggalPeminjaman,TanggalPengembalian,DendaPelanggaran,Status) "
                    + "VALUES('"+No.getText()+"','"+Nama.getText()+"','"+Alamat.getText()+"','"+Jenis.getSelectedItem()+"','"+pinjam+"','"+kembali+"','"+Denda.getText()+"','"+JS+"')";
            int status = KoneksiDB.execute(SQL);
            if(status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else
            {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan!", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int baris = Tabel.getSelectedRow();
        if (baris != -1)
        {
            String NoAnggota = Tabel.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_kembali WHERE NoAnggota='"+No+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else
            {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan!", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else
        {
            JOptionPane.showMessageDialog(this, "Pilih baris data terlebih dahulu!", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        No.setText("");
        Nama.setText("");
        Alamat.setText("");
        Jenis.removeAllItems();
        Judul.setText("");
        TglPinjam.setDate(null);
        TglKembali.setDate(null);
        Denda.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_ClearActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_RefreshActionPerformed

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        // TODO add your handling code here:
        int baris = Tabel.getSelectedRow();
        if (baris != -1)
        {
            No.setText(Tabel.getValueAt(baris, 0).toString());
            Nama.setText(Tabel.getValueAt(baris, 1).toString());
            Alamat.setText(Tabel.getValueAt(baris, 2).toString());
            Jenis.setSelectedItem(Tabel.getValueAt(baris, 3).toString());
            Judul.setText(Tabel.getValueAt(baris, 4).toString());
            Denda.setText(Tabel.getValueAt(baris, 5).toString());
            if ("Kembali".equals(Tabel.getValueAt(baris, 6).toString()))
            {
                rbK.setSelected(true);
            } else
            {
                rbBK.setSelected(true);
            }
        }
    }//GEN-LAST:event_TabelMouseClicked

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Reservasi Pengembalian Buku Perpustakaan Kota Malang");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try
        {
            Tabel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e)
        {
            System.err.format("Cannot Print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new frameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Denda;
    private javax.swing.JComboBox<String> Jenis;
    private javax.swing.JTextField Judul;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField No;
    private javax.swing.JButton Print;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Save;
    private javax.swing.JTable Tabel;
    private javax.swing.JLabel Tanggal;
    private com.toedter.calendar.JDateChooser TglKembali;
    private com.toedter.calendar.JDateChooser TglPinjam;
    private javax.swing.JLabel Waktu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbBK;
    private javax.swing.JRadioButton rbK;
    // End of variables declaration//GEN-END:variables

    private void selectData()
    {
        String kolom[] = {"NoAnggota","NamaPeminjam","AlamatPeminjam","JenisBuku","JudulBuku","TanggalPeminjaman","TanggalPengembalian","DendaPelanggaran","Status"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_kembali";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try
        {
            while (rs.next())
            {
                String NoAnggota = rs.getString(1);
                String NamaPeminjam = rs.getNString(2);
                String AlamatPeminjam = rs.getString(3);
                String JenisBuku = rs.getString(4);
                String JudulBuku = rs.getString(5);
                String TanggalPeminjaman = rs.getString(6);
                String TanggalPengembalian = rs.getString(7);
                String DendaPelanggaran = rs.getString(8);
                String Status = "";
                if ("K".equals(rs.getString(9)))
                {
                    Status = "Kembali";
                } else
                {
                    Status = "BelumKembali";
                }
                String data[] = {NoAnggota,NamaPeminjam,AlamatPeminjam,JenisBuku,JudulBuku,TanggalPeminjaman,TanggalPengembalian,DendaPelanggaran,Status};
                dtm.addRow(data);
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(frameMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        Tabel.setModel(dtm);
    }
    
    public void setTanggal()
    {
        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat cal = new java.text.SimpleDateFormat("dd/MM/yyy");
        Tanggal.setText(cal.format(now));
    }

    public void setJam()
    {
        ActionListener taskPerformer = new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                Date dt = new Date();
                int nilai_hour = dt.getHours();
                int nilai_minute = dt.getMinutes();
                int nilai_second = dt.getSeconds();
                if (nilai_hour <= 9)
                {
                    zero_hour = "0";
                }
                if (nilai_minute <= 9)
                {
                    zero_minute = "0";
                }
                if (nilai_second <= 9)
                {
                    zero_second = "0";
                }
                String hour = zero_hour + Integer.toString(nilai_hour);
                String minute = zero_minute + Integer.toString(nilai_minute);
                String second = zero_second + Integer.toString(nilai_second);
                Waktu.setText("Pukul " + hour + ":" + minute + ":" + second);
            }
        };
        new Timer(100, taskPerformer).start();
    }
}